// Typelizer digest ddd780ac531a15934adf035ed0ede54a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as Routes } from './RoutesController'
export { default as dashboard } from './DashboardController'
export { default as home } from './HomeController'
export { default as identityEmailVerifications } from './Identity/EmailVerificationsController'
export { default as identityPasswordResets } from './Identity/PasswordResetsController'
export { default as sessions } from './SessionsController'
export { default as settingsEmails } from './Settings/EmailsController'
export { default as settingsPasswords } from './Settings/PasswordsController'
export { default as settingsProfiles } from './Settings/ProfilesController'
export { default as settingsSessions } from './Settings/SessionsController'
export { default as turboNativeNavigation } from './Turbo/Native/NavigationController'
export { default as users } from './UsersController'

import _identityPasswordResets from './Identity/PasswordResetsController'
import _identityEmailVerifications from './Identity/EmailVerificationsController'
import _home from './HomeController'
import _sessions from './SessionsController'
import _Routes from './RoutesController'
import _settingsEmails from './Settings/EmailsController'
import _settingsPasswords from './Settings/PasswordsController'
import _settingsProfiles from './Settings/ProfilesController'
import _users from './UsersController'
import _turboNativeNavigation from './Turbo/Native/NavigationController'

export const editIdentityPasswordReset = _identityPasswordResets.edit
export const identityEmailVerification = _identityEmailVerifications.show
export const identityPasswordReset = _identityPasswordResets.update
export const newIdentityPasswordReset = _identityPasswordResets.new
export const root = _home.index
export const session = _sessions.destroy
export const settingsAppearance = _Routes.settingsAppearance
export const settingsEmail = _settingsEmails.show
export const settingsPassword = _settingsPasswords.show
export const settingsProfile = _settingsProfiles.show
export const signIn = _sessions.new
export const signUp = _users.new
export const turboRecedeHistoricalLocation = _turboNativeNavigation.recede
export const turboRefreshHistoricalLocation = _turboNativeNavigation.refresh
export const turboResumeHistoricalLocation = _turboNativeNavigation.resume
