// Typelizer digest b78ace33d03523aa22d9a40abed97e54
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
  locale: string;
}

export type { SharedProps };
